// child_apps/mall-web/src/components/modal/ApprModal/index.jsx
import { useState, useImperativeHandle, forwardRef, useRef } from 'react'
import { Modal, Radio, Form, Input, message } from 'antd'
import StyledModal from '@/components/modal/StyledModal'
import { isPromise } from '@/utils/utils'

/**
注：form中的值
ifApprPass 1 是 2 否
apprNote 说明
 */

/**
 *
 * @param {*} props
 * @param {boolean} [props.isShowNote=true]
 * @param {function} props.onSuccess
 * @returns
 */
function Index(props, ref) {
  const { isShowNote = true, onSuccess } = props

  const [visible, setVisible] = useState(false)
  const [formRef] = Form.useForm()

  const promiseAjaxRef = useRef()
  const [loading, setLoading] = useState(false)
  /**
   *
   * @param {object} options
   * @param {any} options.payload
   * @param {Promise} options.promiseAjax
   */
  function open(options = {}) {
    const { payload = {}, promiseAjax } = options
    setVisible(true)
    if (promiseAjax) {
      promiseAjaxRef.current = function (args) {
        return promiseAjax(payload, args)
      }
    }
  }
  function close() {
    formRef.resetFields()
    setVisible(false)
  }
  async function onOk() {
    const values = await formRef.validateFields()
    if (promiseAjaxRef.current) {
      setLoading(true)
      promiseAjaxRef
        .current(values)
        .finally(() => {
          setLoading(false)
        })
        .then(() => {
          message.success('操作成功')
          onSuccess && onSuccess()
          close()
        })
    }
  }

  useImperativeHandle(ref, () => ({
    open,
  }))

  return (
    <StyledModal title="审核" visible={visible} onCancel={close} onOk={onOk} width={620} confirmLoading={loading} centered={false}>
      <Form form={formRef}>
        <Form.Item name="ifApprPass" label="是否审核通过" initialValue={1}>
          <Radio.Group>
            <Radio value={1}>是</Radio>
            <Radio value={2}>否</Radio>
          </Radio.Group>
        </Form.Item>
        {isShowNote && (
          <Form.Item noStyle shouldUpdate>
            {(form) => {
              const ifApprPassVal = form.getFieldValue('ifApprPass')
              return ifApprPassVal == 1 ? null : (
                <Form.Item name="apprNote" rules={[{ required: true, message: '请输入说明' }]} label="说明">
                  <Input placeholder="请输入说明" allowClear />
                </Form.Item>
              )
            }}
          </Form.Item>
        )}
      </Form>
    </StyledModal>
  )
}

export default forwardRef(Index)

// child_apps/doctor-web/src/views/order/prescriptionMng/ApprModal.vue
<template>
  <StyledModal :visible="visible" title="处方审核" @close="close" @submit="submit" width="700px" :submitLoading="submitLoading">
    <el-form ref="formRef" :model="formModel.form" label-width="100px">
      <el-form-item label="审核" prop="ifPass" :rules="[{ required: true }]">
        <el-radio-group v-model="formModel.form.ifPass">
          <el-radio label="1">审核通过</el-radio>
          <el-radio label="0">审核驳回</el-radio>
        </el-radio-group>
      </el-form-item>
      <el-form-item label="审核意见" prop="apprNote" :rules="[{ required: formModel.form.ifPass == '0', message: '请输入审核意见' }]">
        <el-input v-model="formModel.form.apprNote" type="textarea" placeholder="请输入..." />
      </el-form-item>
    </el-form>

    <div class="detailView_box">
      <detail-view :rxCode="record?.rxCode"></detail-view>
    </div>
  </StyledModal>
</template>

<script>
import { reactive, ref } from 'vue'
import StyledModal from '@/components/modal/StyledModal'
import DetailView from './DetailView/index.vue'
import request from '@/utils/request'
import { validateFormRef } from '@/common/utils_element'
import { ElMessage } from 'element-plus/lib/components'

const defaultForm = {
  ifPass: '1',
  apprNote: '',
}

export default {
  emits: ['success'],
  setup(_, ctx) {
    const visible = ref(false)
    const submitLoading = ref(false)

    const formRef = ref(null)
    const formModel = reactive({
      form: {
        ...defaultForm,
      },
    })

    const record = ref(null)

    function open(pRecord) {
      visible.value = true
      if (pRecord) {
        record.value = pRecord
      }
    }

    function close() {
      record.value = null
      formModel.form = { ...defaultForm }
      visible.value = false
    }

    async function submit() {
      await validateFormRef(formRef)
      const postData = {
        rxCode: record.value?.rxCode,
        ...formModel.form,
      }
      submitLoading.value = true
      request({
        url: '/web/system/prescription/approvePrescription',
        data: postData,
      })
        .finally(() => {
          submitLoading.value = false
        })
        .then((data) => {
          ElMessage.success('操作成功')
          ctx.emit('success')
          close()
        })
    }

    return {
      visible,
      submitLoading,
      open,
      close,
      submit,
      record,
      formRef,
      formModel,
    }
  },
  components: { StyledModal, DetailView },
}
</script>

<style lang="less" scoped>
.detailView_box {
  margin: 20px 0 0 100px;
}
</style>
